GridConfig:
    Width: 5
    Height: 5
    Size: 100

winCondition: 100

plant:
    - type: none
      cost: 0
      price: 0
      growthConditions:
        sun: 0
        water: 0
    - type: mushroom
      cost: 1
      price: 5
      growthConditions:
        sun: 1
        water: 1
    - type: grass
      cost: 3
      price: 8
      growthConditions:
        sun: 3
        water: 5
    - type: pumpkin
      cost: 20
      price: 45
      growthConditions:
        sun: 5
        water: 8

playerPosition:
    x: 0
    y: 0

landColor: 0x926829